<a href="https://colab.research.google.com/github/2303A51405/B6_PFDS_1405/blob/main/PFDS1405.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
a=np.array([1,2,3,4])
print(a)


[1 2 3 4]


In [3]:
b=np.array([[1,2],[3,4]])
print(b)

[[1 2]
 [3 4]]


In [5]:
c = np.zeros((2,2))
print(c)

[[0. 0.]
 [0. 0.]]


In [6]:
d=np.ones((2,3))
print(d)

[[1. 1. 1.]
 [1. 1. 1.]]


In [8]:
range_arr=np.arange(0,10,2)
print("Range Array:",range_arr)

Range Array: [0 2 4 6 8]


In [10]:
rand_arr=np.random.rand(2,3)
print("Random Array:\n",rand_arr)

Random Array:
 [[0.07160437 0.57336698 0.50301277]
 [0.41638574 0.38695537 0.55089301]]


In [13]:
arr=np.array([[1,2,3],[4,5,6]])
print("shape:", arr.shape)
print("Dimension:", arr.ndim)
print("Data type:", arr.dtype)
print("size:", arr.size)
print("Item size:", arr.itemsize)

shape: (2, 3)
Dimension: 2
Data type: int64
size: 6
Item size: 8


In [16]:
arr=np.array([10,20,30,40,50])
print("Frist element:",arr[0])
print("Last element:",arr[-1])
print("slice[1:4]",arr[1:4])
print("Evert secound element:",arr[::2])
print("from secound element:,",arr[1:])

Frist element: 10
Last element: 50
slice[1:4] [20 30 40]
Evert secound element: [10 30 50]
from secound element:, [20 30 40 50]


In [3]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(np.sum(arr))
print(np.max(arr))
print(np.min(arr))
print(np.mean(arr))
print(np.std(arr))
print(np.sum(arr,axis=0))
print(np.sum(arr,axis=1))

21
6
1
3.5
1.707825127659933
[5 7 9]
[ 6 15]


In [5]:
import numpy as np
arr2=np.array([[1,2,3],[4,5,6]])
print("Element at row1,col2:", arr2[0,1])
print("Secound row:", arr2[1, :])
print("Secound column:", arr2[:, 1])

Element at row1,col2: 2
Secound row: [4 5 6]
Secound column: [2 5]
